---
title: '有向無環圖'
author: 'Steven'
date: '2024/09/05, 09/19, 9/26'
output:
    html_document 
    #html_notebook
    #word_document 
    #pdf_document 
    #md_document 
---

## 1. 有向無環圖 (Directed Acyclic Graph, DAG)

* 這次分享基本上取自 [Scott Cunningham - Causal Inference_ The Mixtape (2021)](../references/Scott Cunningham - Causal Inference_ The Mixtape (2021).pdf) 第 3 章

* 圖形因果建模的歷史可以追溯到 20 世紀初的 Sewall Wright, 他是現代遺傳學之父之一，也是經濟學家 Philip Wright 的兒子。

* Sewall 開發了遺傳學路徑圖，而 Philip 則將其應用於計量經濟學識別。然而，經濟學界（與統計學界） 基本上無視了圖形建模在因果推理中的應用。

* 透過電腦科學家、圖靈獎得主 Judea Pearl 的努力，圖形推理在因果推理方面才復興。

    * 他在 [Judea Pearl - Causality (2009, 2nd ed.)](../references/Pearl, Judea - Causality (2009, 2nd ed).pdf) 中解釋了這一點，本書是因果推理的一般理論，闡述了有向圖的用途。

* 圖形模型對設計可靠的**識別** (identification) 策略大有幫助。

### 1-1. 補充: 何謂「識別」？

* 在統計學和計量經濟學中，識別指的是模型的結構參數能夠被唯一且明確地估計出來的條件。

* 具體而言，識別意味著觀察到的數據提供了足夠的資訊，從而使模型中的未知參數能夠被唯一確定。


* 識別問題的三種類型:

    * 完全識別 (Exactly Identified):  
    當數據中提供的資訊（觀測方程的數量）等於模型中未知參數的數量時，模型是完全識別的。此時參數可以唯一確定。

    * 過度識別 (Over-Identified):  
    當數據提供的資訊多於未知參數的數量時，模型是過度識別的。*這通常被視為有利的情況*，因為我們可以檢驗模型的適配度，並確保參數估計的一致性。

    * 未識別 (Under-Identified):  
    當數據提供的資訊少於模型中未知參數的數量時，模型是未識別的。此時，無法唯一確定參數，因為不同的參數組合可能會導致相同的觀察結果。

* 識別的重要性:  
識別是統計建模中的一個核心問題，因為如果模型未識別，無法確定我們所估計的參數是否有意義或能夠反映真實的現象。


### 1-2. 符號說明

* **我們將 DAG 視為因果效應鏈的圖形表示**:  
因果效應本身基於一些潛在的、無法觀察到的結構化過程，所有這些都可以用節點和箭頭等圖形符號表示出來。

    * 節點代表隨機變數，而這些隨機變數假定是由某個資料生成過程 (data generating process) 產生的。
    
    * 箭頭代表兩個隨機變數之間的因果效應，這兩個隨機變數沿著箭頭的直觀方向移動。箭頭的方向反映了因果關係的方向。

* 在 DAG 中，因果關係是單向的。具體而言，它在時間上是向前的。DAG 中沒有迴圈。

    * 要顯示反向因果關係，需要創建多個節點，很可能是同一節點的兩個版本，中間用時間索引隔開。
    
    * 同樣，供需模型中的同時性也不能直接用 DAG 來表示，建議採用不同的方法。
    
* DAG 用反事實來解釋因果關係，**因果效應被定義為世界兩種狀態之間的比較**:  
一種狀態是當某種干預取某些值（實際發生的值），另一種狀態是在干預取其他值（反事實）。

* 因果效應有兩種方式:
    * 直接影響，例如: $D \to Y$
    * 由第三個變數中介 (mediate): $D \to X \to Y$  

* DAG 意在描述與 $D$ 對 $Y$ 的影響相關的所有因果關係:  
既明確描述了因果效應路徑，而*缺少箭頭*表示*缺少因果路徑*。
因此，**DAG 既包含連接變數的箭頭，也包含排除哪些箭頭**。

* 一個完整的 DAG 將包含圖中變數之間的所有直接因果效應，以及圖中任何一對變數的所有共同原因。

### 1-3. 補充: DAG 從何而來？

* 經驗、信念、探索性分析、因果發現...

* DAG 是最新知識的理論表示。這些知識來自於各種不同的來源。例如：科學模型、與專家的對話、自己的觀察和經驗、文獻綜述，以及您自己的直覺和假設。

### 1-4. DAG 的積極意義

* DAG 對於理解先驗知識在確定因果效應中的關鍵作用非常有用。

* DAG 對於交流研究設計和估計方法非常有幫助。

    * 工具變數 (instrument variable)  尤其如此，因為工具變數有非常直觀的 DAG 表示。

    * 透過後門準則 (backdoor criterion)  和對撞 (colliding) 等概念，設計良好的 DAG 可以協助發展出可靠的研究設計，以確定某些干預措施的因果效應。

* DAG 讓我們明白了一個道理：**所有因果效應的識別都需要假設**。
 
## 2. DAG 的正式介紹

### 2-1. 一個簡單的 DAG




